FROM node:24-slim

RUN mkdir -p /app/data

WORKDIR /app

ENV NODE_ENV=production

RUN npm install pm2 -g

COPY dist/ .

RUN npm install --omit=dev

RUN npx prisma generate

EXPOSE 8000

CMD [ "pm2-runtime", "start", "pm2/ecosystem.config.template.json" ]